AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 90 #30

Resources:
  MyServiceAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      Auth:
        #DefaultAuthorizer: MiCognitoAuthorizer
        Authorizers:
          MiCognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/us-east-1_yAxAflKZg

  ProfileApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: org.alfr.LambdaHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: dev
      #SnapStart:
        #ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:dev/myApp/h2-XUFzME
      Events:
        Root:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref MyServiceAPI
            Path: /{proxy+}
            Method: ANY
            Auth:
              Authorizer: MiCognitoAuthorizer